esphome:
  name: plaf108-test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: "plaf108test"

captive_portal:

api: {}

ota:
  - platform: esphome
